# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='File_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=64)),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.File')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('user_type', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='file_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.User'),
        ),
    ]
