# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(max_length=2000)),
                ('share_password', models.CharField(max_length=64)),
                ('share_path', models.CharField(max_length=200)),
                ('share_time', models.CharField(max_length=64)),
                ('File', models.ManyToManyField(to='app02.File')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app02.User')),
            ],
        ),
        migrations.AlterField(
            model_name='file_users',
            name='File',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app02.File'),
        ),
        migrations.AlterField(
            model_name='file_users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app02.User'),
        ),
    ]
