# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20190612_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_users',
            name='File',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.File'),
        ),
        migrations.AlterField(
            model_name='file_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.User'),
        ),
    ]
