# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-12 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_auto_20190612_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='File',
        ),
        migrations.AddField(
            model_name='share',
            name='File_Users',
            field=models.ManyToManyField(to='app02.File_Users'),
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.User'),
        ),
    ]
